# Generated by Django 5.0.7 on 2024-07-18 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pwd', models.CharField(max_length=20, null=True, verbose_name='비밀번호')),
                ('name', models.CharField(max_length=20, null=True, verbose_name='이름')),
                ('score', models.IntegerField(default=0, verbose_name='점수')),
            ],
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(verbose_name='상태')),
                ('attackerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attacker', to='game.users')),
                ('defenderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defender', to='game.users')),
            ],
        ),
    ]
