# Generated by Django 5.0.7 on 2024-07-18 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='attackerCard',
            field=models.IntegerField(default=0, verbose_name='공격자 카드'),
        ),
        migrations.AddField(
            model_name='games',
            name='defenderCard',
            field=models.IntegerField(default=0, verbose_name='방어자 카드'),
        ),
    ]
