# Generated by Django 5.0.7 on 2024-07-19 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='rule',
            field=models.CharField(choices=[('smaller_wins', '숫자가 더 작은 사람이 대결에서 이깁니다'), ('larger_wins', '숫자가 더 큰 사람이 대결에서 이깁니다')], default='larger_wins', max_length=20, verbose_name='규칙'),
        ),
    ]
