# Generated by Django 5.0.7 on 2024-07-19 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='winner',
            field=models.IntegerField(default=0, null=True, verbose_name='승리자'),
        ),
    ]
