# Generated by Django 5.0.7 on 2024-07-19 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_game_rule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='rule',
        ),
    ]
