# Generated by Django 5.0.7 on 2024-07-19 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_game_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='rule_value',
            field=models.IntegerField(null=True, verbose_name='정해진 규칙'),
        ),
    ]
