# Generated by Django 4.2.14 on 2024-07-19 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_game_rule_value'),
        ('game', '0003_remove_game_rule'),
    ]

    operations = [
    ]
