# Generated by Django 5.0.7 on 2024-07-19 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_merge_0002_game_rule_0003_game_rule_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='rule',
        ),
    ]
